### ISSUE TITLE
Vytvořit základní aplikaci využívající lineární layout

### ISSUE THREAD

**Issue by vklucho** [vklucho/github-vk-pma-2024#1]
# TODO
- [x] V gitovské složce našeho projektu v Android Studiu vytvořit projekt s názvem `MyApp01LinearLayout`
- [x] Vytvořit základní lineární layout pomocí xml
- [x] Oživit layout aplikační logikou v kotlinu
![Linear_layout_nahled](https://github.com/user-attachments/assets/78fd08b6-15f2-4526-9327-ab7b8de0f81d)
